------------------------------------------------------------------------------------
-- PROJETO MOVE ON - BANCO DE DADOS ORACLE PL/SQL
-- FINAL PROJECT - CONSOLIDAÇÃO E OTIMIZAÇÃO
-- Autor: Equipe Move ON (Juan Mora, Levi Ochi, Renan Biscola, Vinicius Araujo)
-- Descrição: Estrutura PL/SQL com packages, trigger e dynamic SQL
------------------------------------------------------------------------------------

------------------------------------------------------------------------------------
-- CRIAÇÃO DE TABELAS BASE (simulação de estrutura simplificada)
------------------------------------------------------------------------------------

-- Tabela de usuários
CREATE TABLE usuarios (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(100),
    email           VARCHAR2(100) UNIQUE,
    senha           VARCHAR2(100),
    data_cadastro   DATE DEFAULT SYSDATE
);

-- Tabela de trajetos
CREATE TABLE trajetos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER REFERENCES usuarios(id),
    origem          VARCHAR2(200),
    destino         VARCHAR2(200),
    meio_transporte VARCHAR2(50),
    distancia_km    NUMBER,
    emissao_co2     NUMBER,
    status          VARCHAR2(20) DEFAULT 'EM_ANDAMENTO'
);

-- Tabela de alertas
CREATE TABLE alertas (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER REFERENCES usuarios(id),
    tipo_alerta     VARCHAR2(50),
    mensagem        VARCHAR2(500),
    data_alerta     DATE DEFAULT SYSDATE
);

-- Tabela de auditoria
CREATE TABLE auditoria_trajetos (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id      NUMBER,
    trajeto_id      NUMBER,
    data_hora       DATE,
    acao            VARCHAR2(200)
);

------------------------------------------------------------------------------------
-- PACKAGE: PKG_USUARIOS
------------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_usuarios AS
  PROCEDURE sp_registrar_usuario(p_nome VARCHAR2, p_email VARCHAR2, p_senha VARCHAR2);
  FUNCTION fn_validar_login(p_email VARCHAR2, p_senha VARCHAR2) RETURN BOOLEAN;
END pkg_usuarios;
/

CREATE OR REPLACE PACKAGE BODY pkg_usuarios AS
  PROCEDURE sp_registrar_usuario(p_nome VARCHAR2, p_email VARCHAR2, p_senha VARCHAR2) IS
  BEGIN
    INSERT INTO usuarios (nome, email, senha)
    VALUES (p_nome, p_email, p_senha);
    COMMIT;
  END;

  FUNCTION fn_validar_login(p_email VARCHAR2, p_senha VARCHAR2) RETURN BOOLEAN IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM usuarios
    WHERE email = p_email AND senha = p_senha;

    RETURN (v_count > 0);
  END;
END pkg_usuarios;
/

------------------------------------------------------------------------------------
-- PACKAGE: PKG_ROTAS
------------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_rotas AS
  PROCEDURE sp_registrar_trajeto(
    p_usuario_id NUMBER,
    p_origem VARCHAR2,
    p_destino VARCHAR2,
    p_meio_transporte VARCHAR2,
    p_distancia NUMBER
  );
  FUNCTION fn_calcular_emissao(p_distancia NUMBER, p_meio_transporte VARCHAR2) RETURN NUMBER;
END pkg_rotas;
/

CREATE OR REPLACE PACKAGE BODY pkg_rotas AS
  FUNCTION fn_calcular_emissao(p_distancia NUMBER, p_meio_transporte VARCHAR2) RETURN NUMBER IS
    v_emissao NUMBER;
  BEGIN
    CASE UPPER(p_meio_transporte)
      WHEN 'CARRO' THEN v_emissao := p_distancia * 0.12;
      WHEN 'MOTO' THEN v_emissao := p_distancia * 0.08;
      WHEN 'ONIBUS' THEN v_emissao := p_distancia * 0.05;
      WHEN 'BICICLETA' THEN v_emissao := 0;
      WHEN 'PATINETE' THEN v_emissao := 0;
      ELSE v_emissao := p_distancia * 0.1;
    END CASE;
    RETURN v_emissao;
  END;

  PROCEDURE sp_registrar_trajeto(
    p_usuario_id NUMBER,
    p_origem VARCHAR2,
    p_destino VARCHAR2,
    p_meio_transporte VARCHAR2,
    p_distancia NUMBER
  ) IS
    v_emissao NUMBER;
  BEGIN
    v_emissao := fn_calcular_emissao(p_distancia, p_meio_transporte);

    INSERT INTO trajetos (usuario_id, origem, destino, meio_transporte, distancia_km, emissao_co2)
    VALUES (p_usuario_id, p_origem, p_destino, p_meio_transporte, p_distancia, v_emissao);

    COMMIT;
  END;
END pkg_rotas;
/

------------------------------------------------------------------------------------
-- PACKAGE: PKG_ALERTAS
------------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_alertas AS
  PROCEDURE sp_gerar_alerta(p_usuario_id NUMBER, p_tipo_alerta VARCHAR2, p_mensagem VARCHAR2);
END pkg_alertas;
/

CREATE OR REPLACE PACKAGE BODY pkg_alertas AS
  PROCEDURE sp_gerar_alerta(p_usuario_id NUMBER, p_tipo_alerta VARCHAR2, p_mensagem VARCHAR2) IS
  BEGIN
    INSERT INTO alertas (usuario_id, tipo_alerta, mensagem)
    VALUES (p_usuario_id, p_tipo_alerta, p_mensagem);
    COMMIT;
  END;
END pkg_alertas;
/

------------------------------------------------------------------------------------
-- TRIGGER: TRG_FINALIZA_TRAJETO
------------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_finaliza_trajeto
AFTER UPDATE OF status ON trajetos
FOR EACH ROW
WHEN (NEW.status = 'FINALIZADO')
BEGIN
  INSERT INTO auditoria_trajetos (usuario_id, trajeto_id, data_hora, acao)
  VALUES (:NEW.usuario_id, :NEW.id, SYSDATE, 'Trajeto finalizado automaticamente.');
END;
/

------------------------------------------------------------------------------------
-- PROCEDURE: SP_RELATORIO_DINAMICO (Dynamic SQL)
------------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE sp_relatorio_dinamico(p_filtro IN VARCHAR2) IS
  v_sql VARCHAR2(1000);
  v_cursor SYS_REFCURSOR;
  v_usuario_id NUMBER;
  v_origem VARCHAR2(200);
  v_destino VARCHAR2(200);
  v_meio_transporte VARCHAR2(50);
  v_distancia NUMBER;
  v_emissao NUMBER;
BEGIN
  v_sql := 'SELECT usuario_id, origem, destino, meio_transporte, distancia_km, emissao_co2
            FROM trajetos WHERE ' || p_filtro;

  OPEN v_cursor FOR v_sql;

  LOOP
    FETCH v_cursor INTO v_usuario_id, v_origem, v_destino, v_meio_transporte, v_distancia, v_emissao;
    EXIT WHEN v_cursor%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE('Usuário: ' || v_usuario_id ||
                         ' | Origem: ' || v_origem ||
                         ' | Destino: ' || v_destino ||
                         ' | Transporte: ' || v_meio_transporte ||
                         ' | Distância: ' || v_distancia ||
                         ' km | CO2: ' || v_emissao);
  END LOOP;

  CLOSE v_cursor;
END;
/

------------------------------------------------------------------------------------
-- TESTES BÁSICOS (EXEMPLOS)
------------------------------------------------------------------------------------
-- Inserindo usuários
BEGIN
  pkg_usuarios.sp_registrar_usuario('Juan Mora', 'juan@moveon.com', '1234');
  pkg_usuarios.sp_registrar_usuario('Levi Ochi', 'levi@moveon.com', '1234');
END;
/

-- Registrando trajetos
BEGIN
  pkg_rotas.sp_registrar_trajeto(1, 'Avenida Paulista', 'FIAP Vila Olímpia', 'Bicicleta', 7);
  pkg_rotas.sp_registrar_trajeto(2, 'Pinheiros', 'Centro', 'Carro', 10);
END;
/

-- Gerando alerta
BEGIN
  pkg_alertas.sp_gerar_alerta(1, 'SUSTENTABILIDADE', 'Você evitou 2kg de CO2 usando bicicleta!');
END;
/

-- Atualizando trajeto para testar trigger
UPDATE trajetos SET status = 'FINALIZADO' WHERE id = 1;
/

-- Gerando relatório dinâmico
EXEC sp_relatorio_dinamico('meio_transporte = ''Bicicleta''');
/
------------------------------------------------------------------------------------
-- FIM DO SCRIPT
------------------------------------------------------------------------------------
